### PR TITLE
Fix clang-11 warnings

### LINKED ISSUE #2030: clang-11 gives a number of warnings
Tried self-build clang-11 (very tip of clang master branch):
```
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:87:19: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
    typedef struct
                  ^
                   ExtVASurface
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:89:31: note: type is not C-compatible due to this default member initializer
        VASurfaceID surface = VA_INVALID_SURFACE;
                              ^~~~~~~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1275:28: note: expanded from macro 'VA_INVALID_SURFACE'
#define VA_INVALID_SURFACE      VA_INVALID_ID
                                ^~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1274:24: note: expanded from macro 'VA_INVALID_ID'
#define VA_INVALID_ID           0xffffffff
                                ^~~~~~~~~~
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:98:7: note: type is given name 'ExtVASurface' for linkage purposes by this typedef declaration
    } ExtVASurface;
      ^
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:87:19: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
    typedef struct
                  ^
                   ExtVASurface
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:89:31: note: type is not C-compatible due to this default member initializer
        VASurfaceID surface = VA_INVALID_SURFACE;
                              ^~~~~~~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1275:28: note: expanded from macro 'VA_INVALID_SURFACE'
#define VA_INVALID_SURFACE      VA_INVALID_ID
                                ^~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1274:24: note: expanded from macro 'VA_INVALID_ID'
#define VA_INVALID_ID           0xffffffff
                                ^~~~~~~~~~
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:98:7: note: type is given name 'ExtVASurface' for linkage purposes by this typedef declaration
    } ExtVASurface;
      ^
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:87:19: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
    typedef struct
                  ^
                   ExtVASurface
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:89:31: note: type is not C-compatible due to this default member initializer
        VASurfaceID surface = VA_INVALID_SURFACE;
                              ^~~~~~~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1275:28: note: expanded from macro 'VA_INVALID_SURFACE'
#define VA_INVALID_SURFACE      VA_INVALID_ID
                                ^~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1274:24: note: expanded from macro 'VA_INVALID_ID'
#define VA_INVALID_ID           0xffffffff
                                ^~~~~~~~~~
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:98:7: note: type is given name 'ExtVASurface' for linkage purposes by this typedef declaration
    } ExtVASurface;
      ^
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:87:19: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
    typedef struct
                  ^
                   ExtVASurface
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:89:31: note: type is not C-compatible due to this default member initializer
        VASurfaceID surface = VA_INVALID_SURFACE;
                              ^~~~~~~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1275:28: note: expanded from macro 'VA_INVALID_SURFACE'
#define VA_INVALID_SURFACE      VA_INVALID_ID
                                ^~~~~~~~~~~~~
/opt/intel/git/install/include/va/va.h:1274:24: note: expanded from macro 'VA_INVALID_ID'
#define VA_INVALID_ID           0xffffffff
                                ^~~~~~~~~~
/opt/intel/git/msdk/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h:98:7: note: type is given name 'ExtVASurface' for linkage purposes by this typedef declaration
    } ExtVASurface;
      ^


/opt/intel/git/msdk/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:6276:69: warning: bitwise or with non-zero value always evaluates to true [-Wtautological-bitwise-compare]
    if (true == executeParams.bSceneDetectionEnable && (FRC_ENABLED | config.m_extConfig.mode))
                                                        ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~

                                                        
/opt/intel/git/msdk/_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp:2810:9: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
        if (((fo + 1) % gopPicSize == 0 && (gopOptFlag & MFX_GOP_CLOSED)) ||
        ^
/opt/intel/git/msdk/_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_utils.cpp:2806:5: note: previous statement is here
    if (fo % gopPicSize % gopRefDist == 0)
    ^


      
/opt/intel/git/msdk/_studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp:124:60: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]
                if (mask != MFX_IOPATTERN_OUT_VIDEO_MEMORY || mask != MFX_IOPATTERN_OUT_SYSTEM_MEMORY || mask != MFX_IOPATTERN_OUT_OPAQUE_MEMORY)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



      
/opt/intel/git/msdk/_studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp:124:60: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]
                if (mask != MFX_IOPATTERN_OUT_VIDEO_MEMORY || mask != MFX_IOPATTERN_OUT_SYSTEM_MEMORY || mask != MFX_IOPATTERN_OUT_OPAQUE_MEMORY)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by aobolensk**
resolves #2030

### CODE REVIEW

File: _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp [hunk 1]
```diff
@@ -121,7 +121,7 @@ mfxStatus MFXVC1DecCommon::Query(VideoCORE* core, mfxVideoParam *in, mfxVideoPar
                 (in->IOPattern & MFX_IOPATTERN_OUT_OPAQUE_MEMORY))
             {
                 uint32_t mask = in->IOPattern & 0xf0;
-                if (mask != MFX_IOPATTERN_OUT_VIDEO_MEMORY || mask != MFX_IOPATTERN_OUT_SYSTEM_MEMORY || mask != MFX_IOPATTERN_OUT_OPAQUE_MEMORY)
+                if (mask != MFX_IOPATTERN_OUT_VIDEO_MEMORY && mask != MFX_IOPATTERN_OUT_SYSTEM_MEMORY && mask != MFX_IOPATTERN_OUT_OPAQUE_MEMORY)
```
Comment (fzhar) [inline _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp]: Logic is changed here. Is it done on purpose ?

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp [hunk 2]
```diff
@@ -6273,7 +6273,7 @@ mfxStatus ConfigureExecuteParams(
     }
 
 
-    if (true == executeParams.bSceneDetectionEnable && (FRC_ENABLED | config.m_extConfig.mode))
+    if (true == executeParams.bSceneDetectionEnable && (FRC_ENABLED & config.m_extConfig.mode))
```
Comment (fzhar) [inline _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Logic is changed here. Is it done on purpose ?

Comment (aobolensk) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]:
```cpp
(FRC_ENABLED | config.m_extConfig.mode)
```
This condition is always true. I thought '&' is meant to be here, because FrcMode enum contains bitmasks.

File: _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp (hunk 1 above)
Comment (aobolensk) [reply _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp]: I took a closer look to that. This condition on line 120 seems to be not needed, because there's another similar condition after on line 182.
```cpp
        if ((in->IOPattern & MFX_IOPATTERN_OUT_SYSTEM_MEMORY) ||
            (in->IOPattern & MFX_IOPATTERN_OUT_VIDEO_MEMORY) ||
            (in->IOPattern & MFX_IOPATTERN_OUT_OPAQUE_MEMORY))
            out->IOPattern = in->IOPattern;
```
And it overrides results of this assignment to `out->IOPattern` anyway and `in->IOPattern` value is not changed and `out->IOPattern` value is not used between this section and line 182.
So I'm going to remove this condition.

File: _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp [hunk 3]
```diff
@@ -117,14 +117,6 @@ mfxStatus MFXVC1DecCommon::Query(VideoCORE* core, mfxVideoParam *in, mfxVideoPar
                 break;
             }
 
-            if ((in->IOPattern & MFX_IOPATTERN_OUT_SYSTEM_MEMORY) || (in->IOPattern & MFX_IOPATTERN_OUT_VIDEO_MEMORY) ||
```
Comment (mgonchar) [inline _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp]: well, it's obvious that previous code had logic issue, but I don't think that we should remove this piece completely. Most likely it should be done similarly with other codecs, see [here](https://github.com/Intel-Media-SDK/MediaSDK/blob/95e1735206bfd91cb5c6ae809ebb85c87f0db599/_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp#L777)

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp (hunk 2 above)
Comment (mgonchar) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: also we can remove ```true ==``` as it don't have any sense as for me

File: _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp (hunk 3 above)
Comment (aobolensk) [reply _studio/mfx_lib/shared/src/mfx_vc1_dec_common.cpp]: Setting 'unsupported' status definitely makes sense.

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp (hunk 2 above)
Comment (aobolensk) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Done

File: builder/ConfTargets.cmake [hunk 4]
```diff
@@ -23,6 +23,8 @@ message( STATUS "Global Configuration of Targets" )
 set( T_ARCH "sse4.2" )
 message( STATUS "Target Architecture to compile: ${T_ARCH}" )
 
+set( CMAKE_ASM_FLAGS_RELEASE "-O3" )
```
Comment (dvrogozh) [inline builder/ConfTargets.cmake]: was that a warning fix as well? which?

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp [hunk 5]
```diff
@@ -6273,7 +6273,7 @@ mfxStatus ConfigureExecuteParams(
     }
 
 
-    if (true == executeParams.bSceneDetectionEnable && (FRC_ENABLED | config.m_extConfig.mode))
+    if (executeParams.bSceneDetectionEnable && (FRC_ENABLED & config.m_extConfig.mode))
```
Comment (dvrogozh) [inline _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Hm. warning was that condition is always true, so did we execute unintended code sometimes? This change might require validation? which tests did you run?

File: builder/ConfTargets.cmake (hunk 4 above)
Comment (aobolensk) [reply builder/ConfTargets.cmake]: CMAKE_ASM_FLAGS_RELEASE contains "-O3 -DNDEBUG" by default.
And now during compilation assembly files clang says that "-D NDEBUG" option is unused.

Comment (dvrogozh) [reply builder/ConfTargets.cmake]: As a major rule: you can _not_ override potential user input. And you are doing exactly that by this `set()`.

I think we were handling this issue somehow - please, check with our CI how we actually call cmake for clang. In any case - please, drop this change. Let's focus on other issues rather than this one.

Comment (aobolensk) [reply builder/ConfTargets.cmake]: Ok, got it

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp (hunk 5 above)
Comment (aobolensk) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: > did we execute unintended code sometimes?

Yes, I suppose. I think that condition like that: 
```cpp
    if (executeParams.bSceneDetectionEnable)
        executeParams.bSceneDetectionEnable = false;
```
doesn't make any sense. But I need to dive into investigation of these params.

Comment (dvrogozh) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Actually, `bSceneDetectionEnable` is never used:
```
[dvrogozh@dvrscl msdk]$ fgrep -rsn bSceneDetectionEnable _studio/
_studio/mfx_lib/vpp/src/mfx_vpp_jpeg_d3d9.cpp:58:    pMfxExecuteParams->bSceneDetectionEnable = false;
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:131:    pMfxExecuteParams->bSceneDetectionEnable = false;
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:6181:                    executeParams.bSceneDetectionEnable = false;
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:6276:    if (true == executeParams.bSceneDetectionEnable && (FRC_ENABLED | config.m_extConfig.mode))
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:6279:        executeParams.bSceneDetectionEnable = false;
_studio/shared/include/mfx_vpp_interface.h:278:               ,bSceneDetectionEnable(false)
_studio/shared/include/mfx_vpp_interface.h:345:                    bSceneDetectionEnable != false ||
_studio/shared/include/mfx_vpp_interface.h:401:        bool           bSceneDetectionEnable;
```

So, the fix should be: delete them all! :)

Comment (aobolensk) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Done.

File: _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp [hunk 6]
```diff
@@ -6178,7 +6177,6 @@ mfxStatus ConfigureExecuteParams(
                 }
                 else if (MFX_EXTBUFF_VPP_SCENE_ANALYSIS == bufferId)
                 {
-                    executeParams.bSceneDetectionEnable = false;
                 }
```
Comment (aobolensk) [inline _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: This empty 'else if' branch looks suspicious. I can't remove it without changing something else, because on some tests it falls to last else branch and MFX_ERR_INVALID_VIDEO_PARAM is produced.

Comment (dvrogozh) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: That's ok. Please, file another issue here on github requesting to clarify whether MFX_EXTBUFF_VPP_SCENE_ANALYSIS is actually supported (I suspect not).  We will let out VP team to handle that. Post a link here.

Comment (aobolensk) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: Created #2053

Comment (dvrogozh) [reply _studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp]: cool. I think current PR is done. +1.
