### PR TITLE
[MPEGe][Linux] pass target bitrate to driver only for VBR

### LINKED ISSUE #2622: [regression] MPEGe CQP quality drop/artifacts since #2621
Since #2621, MPEG CQP encoding quality has dropped with visual artifacts.

```
# generate a raw input file
$ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
   ! video/x-raw,format=I420,width=1920,height=1080 \
   ! filesink location=i420.yuv

# encode
$ gst-launch-1.0 -vf filesrc location=./i420.yuv num-buffers=10 \ 
   ! rawvideoparse format=i420 width=1920 height=1080 \
   ! videoconvert ! video/x-raw,format=NV12 \
   ! msdkmpeg2enc rate-control=cqp gop-size=1 qpi=14 qpp=14 qpb=14 target-usage=4 b-frames=0 \
   ! video/mpeg,mpegversion=2 ! mpegvideoparse \
   ! filesink location=gst-msdk.mpg

# decode
$ gst-launch-1.0 -vf filesrc location=gst-msdk.mpg \
   ! mpegvideoparse ! msdkmpeg2dec \
   ! videoconvert ! video/x-raw,format=I420 \
   ! filesink location=gst-msdk.yuv

# check psnr
$ metrics_calc_lite -i1 ./i420.yuv -i2 ./gst-msdk.yuv -w 1920 -h 1080 apsnr all
```

Before #2621:
```
<avg_metric=Y-APSNR> 40.11147</avg_metric>
<avg_metric=U-APSNR> 53.21119</avg_metric>
<avg_metric=V-APSNR> 53.98439</avg_metric>
<avg_metric=APSNR> 41.77578</avg_metric>
```

After #2621:
```
<avg_metric=Y-APSNR> 23.68770</avg_metric>
<avg_metric=U-APSNR> 27.50229</avg_metric>
<avg_metric=V-APSNR> 28.23502</avg_metric>
<avg_metric=APSNR> 24.68727</avg_metric>
```

This regression can also be reproduced with ffmpeg.

### PR DESCRIPTION
**Pull request by lakulako**
Fixes recent commit #2621
Fixes #2622 issue

### CODE REVIEW

File: _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp [hunk 1]
```diff
@@ -961,14 +961,17 @@ mfxStatus VAAPIEncoder::FillMiscParameterBuffer(ExecuteBuffers* pExecuteBuffers)
...
+    {
+        vaSts = vaCreateBuffer(m_vaDisplay,
+            m_vaContextEncode,
+            VAEncMiscParameterBufferType,
+            sizeof(VAEncMiscParameterRateControl) + sizeof(VAEncMiscParameterBuffer),
+            1,
+            m_pMiscParamsBrc,
+            &m_miscParamBrcId);
+        MFX_CHECK_WITH_ASSERT(VA_STATUS_SUCCESS == vaSts, MFX_ERR_DEVICE_FAILED);
+    }
```
Comment (dmitryermilov) [inline _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp:975]: @vilichev , I recall you fixed a similar issue in HEVC. If so, can you please review the PR?

Comment (dmitryermilov) [reply _studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp:975]: seems it was another issue (https://github.com/Intel-Media-SDK/MediaSDK/pull/2439)

**Review by dmitryermilov — APPROVED** [review]

**Review by vilichev — DISMISSED** [review]

**Review by dmitryermilov — CHANGES_REQUESTED** [review]
@lakulako , please add 'Fixes #2622' to commit message

**Review by vilichev — APPROVED** [review]

**Review by dmitryermilov — APPROVED** [review]
