### PR TITLE
samples: enable max slice size for H.265

### LINKED ISSUE #1778: sample_encode and sample_multi_transcode don't support HEVC with MaxSliceSize
iHD supports MaxSliceSize on ICL, however both sample_encode and sample_multi_transcode don't support MaxSliceSize for HEVC. 

$> /usr/share/mfx/samples/sample_multi_transcode -qsv-ff -mss 10000 -i::h264 input.h264 -o::h265 output.h264

ERROR: MaxSliceSize option is supported only with H.264 encoder!

$> /usr/share/mfx/samples/sample_encode h265 -qsv-ff -nv12 -mss 10000 -i input.yuv -o output.h264 -w 1920 -h 1080

ERROR: MaxSliceSize option is supported only with H.264 encoder!

### PR DESCRIPTION
**Pull request by YurSkur**
Fixes #1778 (sample_encode and sample_multi_transcode don't support HEVC with MaxSliceSize)

### CODE REVIEW

File: samples/sample_encode/src/sample_encode.cpp [hunk 1]
```diff
@@ -1433,7 +1433,7 @@ mfxStatus ParseInputString(msdk_char* strInput[], mfxU8 nArgNum, sInputParams* p
     //    return MFX_ERR_UNSUPPORTED;
     //}
 
-    if ((pParams->nMaxSliceSize) && (pParams->CodecId != MFX_CODEC_AVC))
+    if ((pParams->nMaxSliceSize) && !((pParams->CodecId != MFX_CODEC_AVC) || (pParams->CodecId != MFX_CODEC_HEVC)))
```
Comment (mgonchar) [inline samples/sample_encode/src/sample_encode.cpp]: It is always false condition.

Following De Morgan's laws !(A || B) is same as !A && !B, i.e.
```
(pParams->CodecId == MFX_CODEC_AVC) && (pParams->CodecId == MFX_CODEC_HEVC)
```

I believe correct condition is
```
if ((pParams->nMaxSliceSize) && ((pParams->CodecId != MFX_CODEC_AVC) || (pParams->CodecId != MFX_CODEC_HEVC)))
```

File: samples/sample_multi_transcode/src/transcode_utils.cpp [hunk 2]
```diff
@@ -2647,7 +2647,7 @@ mfxStatus CmdProcessor::VerifyAndCorrectInputParams(TranscodingSample::sInputPar
     {
         PrintError(MSDK_STRING("-mss and -l options are not compatible!"));
     }
-    if ((InputParams.nMaxSliceSize) && (InputParams.EncodeId != MFX_CODEC_AVC))
+    if ((InputParams.nMaxSliceSize) && !((InputParams.EncodeId != MFX_CODEC_AVC) || (InputParams.EncodeId != MFX_CODEC_HEVC)))
```
Comment (mgonchar) [inline samples/sample_multi_transcode/src/transcode_utils.cpp]: same here

File: samples/sample_encode/src/sample_encode.cpp (hunk 1 above)
Comment (YurSkur) [reply samples/sample_encode/src/sample_encode.cpp]: fixed

File: samples/sample_multi_transcode/src/transcode_utils.cpp (hunk 2 above)
Comment (YurSkur) [reply samples/sample_multi_transcode/src/transcode_utils.cpp]: fixed

File: samples/sample_encode/src/sample_encode.cpp [hunk 3]
```diff
@@ -1433,9 +1433,9 @@ mfxStatus ParseInputString(msdk_char* strInput[], mfxU8 nArgNum, sInputParams* p
     //    return MFX_ERR_UNSUPPORTED;
     //}
 
-    if ((pParams->nMaxSliceSize) && (pParams->CodecId != MFX_CODEC_AVC))
+    if ((pParams->nMaxSliceSize) && !((pParams->CodecId == MFX_CODEC_AVC) || (pParams->CodecId == MFX_CODEC_HEVC)))
```
Comment (mgonchar) [inline samples/sample_encode/src/sample_encode.cpp]: honestly, I think that
```
if (pParams->nMaxSliceSize && (pParams->CodecId != MFX_CODEC_AVC) && (pParams->CodecId != MFX_CODEC_HEVC))
```
is much better

Comment (YurSkur) [reply samples/sample_encode/src/sample_encode.cpp]: done
