### PR TITLE
Fix missing field initialization in mfx_dispatcher_log

### LINKED ISSUE #1304: dispatcher: field initialization missed
api/mfx_dispatch/windows/include/mfx_dispatcher_log.h
    FILE * m_hdl;

### PR DESCRIPTION
**Pull request by aobolensk**
Initialize m_hdl FILE pointer with nullptr.
Closes #1304

### CODE REVIEW

File: api/mfx_dispatch/windows/include/mfx_dispatcher_log.h [hunk 1]
```diff
@@ -250,7 +250,7 @@ class FileSink
             fclose(m_hdl);
     }
 private:
-    FILE * m_hdl;
+    FILE * m_hdl = nullptr;
```
Comment (dvrogozh) [inline api/mfx_dispatch/windows/include/mfx_dispatcher_log.h]: if you use nullptr, use everywhere. Change line 249 accordingly, please.

**Comment by dmitryermilov** [comment]
>should be C++03 because of compiler restriction

@eponomar , do we check VS 2015 build of the dispatcher in CI?
