### PR TITLE
[tutorials_common] Add Encode and VPP response handling in _simple_free

### LINKED ISSUE #1984: Memory leaks in simple_3_encode_vmem tutorial
Hi,

During stress tests (100+ runs in a single process) I've found that `simple_3_encode_vmem` code is leaking memory. This is confirmed by using `valgrind` to trace memory leaks.

If I read the results correctly, looks like this function is for responsible for the leaked memory allocation:

```c
mfxStatus _simple_alloc(mfxFrameAllocRequest* request,
                        mfxFrameAllocResponse* response)
```
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tutorials/common/common_vaapi.cpp#L244

This is a piecie of code that should free this memory block, but apparently it doesn't work:

```c
mfxAllocator.Free(mfxAllocator.pthis, &mfxResponse);
```

https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tutorials/simple_3_encode_vmem/src/simple_encode_vmem.cpp#L300

The issue is not present in `simple_3_encode` that does not use MFX memory allocation.

Full valgrind log is here:

```
swm@swm-Latitude-E7470:~$ valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./msdk/build/__bin/release/simple_3_encode_vmem -hw -g 176x96 -b 1000 -f 30/1 /home/swm/Downloads/test_stream_176x96.yuv t.h264
==18181== Memcheck, a memory error detector
==18181== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==18181== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==18181== Command: ./msdk/build/__bin/release/simple_3_encode_vmem -hw -g 176x96 -b 1000 -f 30/1 /home/swm/Downloads/test_stream_176x96.yuv t.h264
==18181== 
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
==18181== Thread 2:
==18181== Conditional jump or move depends on uninitialised value(s)
==18181==    at 0x5412F9B: ??? (in /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.30)
==18181==    by 0x53B38D4: ??? (in /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.30)
==18181==    by 0x53B6AC8: ??? (in /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.30)
==18181==    by 0x525CD05: ??? (in /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.30)
==18181==    by 0x4997F73: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==18181==    by 0x48A5668: start_thread (pthread_create.c:479)
==18181==    by 0x4D3A322: clone (clone.S:95)
==18181==  Uninitialised value was created by a stack allocation
==18181==    at 0x53CD6F0: ??? (in /usr/lib/x86_64-linux-gnu/libmfxhw64.so.1.30)
==18181== 
Frame number: 101
Execution time: 8.74 s (11.56 fps)
==18181== 
==18181== HEAP SUMMARY:
==18181==     in use at exit: 9,458 bytes in 26 blocks
==18181==   total heap usage: 10,127 allocs, 10,101 frees, 1,644,204,812 bytes allocated
==18181== 
==18181== Thread 1:
==18181== 16 bytes in 1 blocks are indirectly lost in loss record 1 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F5F4: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:244)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x5290D97: ???
==18181==    by 0x53C4FCC: ???
==18181==    by 0x53B160A: ???
==18181==    by 0x53B2AFA: ???
==18181==    by 0x5261B3A: ???
==18181==    by 0x10BEAB: Init (mfxvideo++.h:81)
==18181==    by 0x10BEAB: main (simple_encode_vmem.cpp:167)
==18181== 
==18181== 36 bytes in 1 blocks are indirectly lost in loss record 2 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F5F4: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:244)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x10BCE3: main (simple_encode_vmem.cpp:150)
==18181== 
==18181== 48 bytes in 1 blocks are still reachable in loss record 3 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x400CCA7: _dl_new_object (dl-object.c:163)
==18181==    by 0x4006A27: _dl_map_object_from_fd (dl-load.c:986)
==18181==    by 0x4009FFE: _dl_map_object (dl-load.c:2461)
==18181==    by 0x40150C3: dl_open_worker (dl-open.c:228)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x4D7BDD2: _dl_catch_error (dl-error-skeleton.c:215)
==18181==    by 0x485DB58: _dlerror_run (dlerror.c:170)
==18181==    by 0x485D3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==18181== 
==18181== 48 bytes in 1 blocks are still reachable in loss record 4 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x401E34E: strdup (strdup.c:42)
==18181==    by 0x4009F8B: _dl_map_object (dl-load.c:2393)
==18181==    by 0x40150C3: dl_open_worker (dl-open.c:228)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x4D7BDD2: _dl_catch_error (dl-error-skeleton.c:215)
==18181==    by 0x485DB58: _dlerror_run (dlerror.c:170)
==18181==    by 0x485D3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==18181==    by 0x4865F60: ??? (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181== 
==18181== 112 bytes in 3 blocks are still reachable in loss record 5 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x401E34E: strdup (strdup.c:42)
==18181==    by 0x40188F1: _dl_load_cache_lookup (dl-cache.c:320)
==18181==    by 0x400A361: _dl_map_object (dl-load.c:2327)
==18181==    by 0x400EB34: openaux (dl-deps.c:64)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x400EF82: _dl_map_object_deps (dl-deps.c:248)
==18181==    by 0x4015128: dl_open_worker (dl-open.c:271)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181== 
==18181== 112 bytes in 3 blocks are still reachable in loss record 6 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x400CCA7: _dl_new_object (dl-object.c:163)
==18181==    by 0x4006A27: _dl_map_object_from_fd (dl-load.c:986)
==18181==    by 0x4009FFE: _dl_map_object (dl-load.c:2461)
==18181==    by 0x400EB34: openaux (dl-deps.c:64)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x400EF82: _dl_map_object_deps (dl-deps.c:248)
==18181==    by 0x4015128: dl_open_worker (dl-open.c:271)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181== 
==18181== 208 bytes in 1 blocks are still reachable in loss record 7 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x4014662: add_to_global (dl-open.c:104)
==18181==    by 0x4015677: dl_open_worker (dl-open.c:526)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x4D7BDD2: _dl_catch_error (dl-error-skeleton.c:215)
==18181==    by 0x485DB58: _dlerror_run (dlerror.c:170)
==18181==    by 0x485D3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==18181==    by 0x4865F60: ??? (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x48671DF: vaInitialize (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181== 
==18181== 368 bytes in 1 blocks are indirectly lost in loss record 8 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x84E06B2: ??? (in /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0)
==18181==    by 0x7D7786E: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7D780F3: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x4867CD6: vaCreateSurfaces (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x10F77C: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:259)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x10BCE3: main (simple_encode_vmem.cpp:150)
==18181== 
==18181== 512 bytes in 1 blocks are indirectly lost in loss record 9 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x84E0B04: ??? (in /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0)
==18181==    by 0x84E0DE6: ??? (in /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0)
==18181==    by 0x7DAD481: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7DAD5F1: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7D73CE5: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7D7DA84: __vaDriverInit_1_4 (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x48661A4: ??? (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x48671DF: vaInitialize (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x10F428: CreateVAEnvDRM(void**) (common_vaapi.cpp:145)
==18181==    by 0x10EC66: Initialize(int, mfxVersion, MFXVideoSession*, mfxFrameAllocator*, bool) (common_utils_linux.cpp:43)
==18181==    by 0x10BBA4: main (simple_encode_vmem.cpp:96)
==18181== 
==18181== 608 bytes in 1 blocks are indirectly lost in loss record 10 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F604: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:246)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x5290D97: ???
==18181==    by 0x53C4FCC: ???
==18181==    by 0x53B160A: ???
==18181==    by 0x53B2AFA: ???
==18181==    by 0x5261B3A: ???
==18181==    by 0x10BEAB: Init (mfxvideo++.h:81)
==18181==    by 0x10BEAB: main (simple_encode_vmem.cpp:167)
==18181== 
==18181== 656 (32 direct, 624 indirect) bytes in 1 blocks are definitely lost in loss record 11 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F614: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:247)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x5290D97: ???
==18181==    by 0x53C4FCC: ???
==18181==    by 0x53B160A: ???
==18181==    by 0x53B2AFA: ???
==18181==    by 0x5261B3A: ???
==18181==    by 0x10BEAB: Init (mfxvideo++.h:81)
==18181==    by 0x10BEAB: main (simple_encode_vmem.cpp:167)
==18181== 
==18181== 944 (64 direct, 880 indirect) bytes in 1 blocks are definitely lost in loss record 12 of 17
==18181==    at 0x483A7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x84E0AB5: ??? (in /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0)
==18181==    by 0x84E0DE6: ??? (in /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0)
==18181==    by 0x7DAD481: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7DAD5F1: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7D73CE5: ??? (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x7D7DA84: __vaDriverInit_1_4 (in /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so)
==18181==    by 0x48661A4: ??? (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x48671DF: vaInitialize (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x10F428: CreateVAEnvDRM(void**) (common_vaapi.cpp:145)
==18181==    by 0x10EC66: Initialize(int, mfxVersion, MFXVideoSession*, mfxFrameAllocator*, bool) (common_utils_linux.cpp:43)
==18181==    by 0x10BBA4: main (simple_encode_vmem.cpp:96)
==18181== 
==18181== 1,056 bytes in 4 blocks are still reachable in loss record 13 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x401274A: _dl_check_map_versions (dl-version.c:274)
==18181==    by 0x401545C: dl_open_worker (dl-open.c:277)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x4D7BDD2: _dl_catch_error (dl-error-skeleton.c:215)
==18181==    by 0x485DB58: _dlerror_run (dlerror.c:170)
==18181==    by 0x485D3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==18181==    by 0x4865F60: ??? (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181==    by 0x48671DF: vaInitialize (in /usr/lib/x86_64-linux-gnu/libva.so.2.500.0)
==18181== 
==18181== 1,224 bytes in 1 blocks are still reachable in loss record 14 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x400C9E1: _dl_new_object (dl-object.c:73)
==18181==    by 0x4006A27: _dl_map_object_from_fd (dl-load.c:986)
==18181==    by 0x4009FFE: _dl_map_object (dl-load.c:2461)
==18181==    by 0x40150C3: dl_open_worker (dl-open.c:228)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x4D7BDD2: _dl_catch_error (dl-error-skeleton.c:215)
==18181==    by 0x485DB58: _dlerror_run (dlerror.c:170)
==18181==    by 0x485D3D9: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==18181== 
==18181== 1,368 bytes in 1 blocks are indirectly lost in loss record 15 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F604: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:246)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x10BCE3: main (simple_encode_vmem.cpp:150)
==18181== 
==18181== 1,476 (72 direct, 1,404 indirect) bytes in 1 blocks are definitely lost in loss record 16 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x10F614: _simple_alloc(mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:247)
==18181==    by 0x1103CF: simple_alloc(void*, mfxFrameAllocRequest*, mfxFrameAllocResponse*) (common_vaapi.cpp:351)
==18181==    by 0x10BCE3: main (simple_encode_vmem.cpp:150)
==18181== 
==18181== 3,574 bytes in 3 blocks are still reachable in loss record 17 of 17
==18181==    at 0x483CD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==18181==    by 0x400C9E1: _dl_new_object (dl-object.c:73)
==18181==    by 0x4006A27: _dl_map_object_from_fd (dl-load.c:986)
==18181==    by 0x4009FFE: _dl_map_object (dl-load.c:2461)
==18181==    by 0x400EB34: openaux (dl-deps.c:64)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x400EF82: _dl_map_object_deps (dl-deps.c:248)
==18181==    by 0x4015128: dl_open_worker (dl-open.c:271)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181==    by 0x40149B9: _dl_open (dl-open.c:603)
==18181==    by 0x485D34B: dlopen_doit (dlopen.c:66)
==18181==    by 0x4D7BD38: _dl_catch_exception (dl-error-skeleton.c:196)
==18181== 
==18181== LEAK SUMMARY:
==18181==    definitely lost: 168 bytes in 3 blocks
==18181==    indirectly lost: 2,908 bytes in 6 blocks
==18181==      possibly lost: 0 bytes in 0 blocks
==18181==    still reachable: 6,382 bytes in 17 blocks
==18181==         suppressed: 0 bytes in 0 blocks
==18181== 
==18181== For lists of detected and suppressed errors, rerun with: -s
==18181== ERROR SUMMARY: 104 errors from 4 contexts (suppressed: 0 from 0)
```

### PR DESCRIPTION
**Pull request by egorovdanil**
Fixes #1984

Signed-off-by: egorovdanil <danil.egorov@intel.com>

### CODE REVIEW

File: tutorials/common/common_vaapi.cpp [hunk 1]
```diff
@@ -512,12 +512,19 @@ mfxStatus _simple_free(mfxHDL pthis, mfxFrameAllocResponse* response)
...
-        allocDecodeResponses[pthis].refCount--;
-        if (0 == allocDecodeResponses[pthis].refCount)
-            actualFreeMemory = true;
-    }; // else actualFreeMemory = true;
+
+    if (--allocDecodeResponses[pthis].refCount == 0) {
+        // Decode free response handling
+        if (0 == memcmp(response, &(allocDecodeResponses[pthis].mfxResponse),
+                        sizeof(*response))) {
+            allocDecodeResponses[pthis].refCount--;
```
Comment (mgonchar) [inline tutorials/common/common_vaapi.cpp]: You have already decremented this counter to zero at line 516

Comment (egorovdanil) [reply tutorials/common/common_vaapi.cpp]: @mgonchar, fixed
