### PR TITLE
Fix infinite loop for Ref 4 @ L5.2

### LINKED ISSUE #2325: [ffmpeg-qsv][gst-msdk][regression]the MediaSDK commit:e126273431b470a738e4c26896b829a6801cb455 will cause regression.
Our CI shows that the MediaSDK commit :  e126273431b470a738e4c26896b829a6801cb455 will cause  **ffmpeg-qsv/gst-msdk avc decode** regression. 
For gst-msdk:
MediaSDK-**e126273431b47**
gst-msdk.decode.avc         total:310      pass:305     **fail:5**
MediaSDK-**995f036b7ab00e**
gst-msdk.decode.avc         total:310      pass:307     **fail:3** 
We hope to get your help.
thanks~

### PR DESCRIPTION
**Pull request by uartie**
This fixes an infinite loop when an AVC stream has
4 ref frames and level 5.2... regression introduced
by:

```
commit e126273431b470a738e4c26896b829a6801cb455
Author: Guo, Will <will.guo@intel.com>
Date:   Sun Apr 26 19:22:34 2020 +0800

    Support AVC Level 6/6.1/6.2

    Support Decode AVC Level 6/6.1/6.2

    Issue: MDP-47088

    Change-Id: I42aa5f67b7480a264f86822d5e5e3cd750d8d090
```

Fixes #2325

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h [hunk 1]
```diff
@@ -788,19 +785,19 @@ inline int32_t CalculateDPBSize(uint8_t & level_idc, int32_t width, int32_t heig
...
         case H264VideoDecoderParams::H264_LEVEL_61:
         case H264VideoDecoderParams::H264_LEVEL_62:
-            level_idc = H264VideoDecoderParams::H264_LEVEL_MAX;
-            break;
+            // fall-through
 #endif
+        // Set level_idc to INTERNAL_MAX_LEVEL so that MaxDPBMbs = 696320
+        // can be used to calculate the DPB size.
+        case H264VideoDecoderParams::H264_LEVEL_51:
+        case H264VideoDecoderParams::H264_LEVEL_52:
```
Comment (dmitryermilov) [inline _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:797]: If I got right this change was a root cause of the regression from https://github.com/Intel-Media-SDK/MediaSDK/commit/e126273431b470a738e4c26896b829a6801cb455:
```
        case H264VideoDecoderParams::H264_LEVEL_52:
-            level_idc = INTERNAL_MAX_LEVEL;
+           level_idc = H264VideoDecoderParams::H264_LEVEL_52;
```
and you restored it back. 
Thank you @uartie !

**Review by dmitryermilov — APPROVED** [review]

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h (hunk 1 above)
Comment (uartie) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:797]: right.

Comment (uartie) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:797]: I think I will move these cases back up so they remain in increasing order.

Comment (uartie) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h]: updated.

**Comment by uartie** [comment]
@dmitryermilov can you do another quick review for my update?

**Review by dmitryermilov — APPROVED** [review]

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h [hunk 2]
```diff
@@ -728,12 +728,9 @@ inline int32_t CalculateDPBSize(uint8_t & level_idc, int32_t width, int32_t heig
         case H264VideoDecoderParams::H264_LEVEL_6:
         case H264VideoDecoderParams::H264_LEVEL_61:
         case H264VideoDecoderParams::H264_LEVEL_62:
-            MaxDPBMbs = 696320;
-            break;
+            // fall-through
```
Comment (guowillyy) [inline _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:731]: Seems issue could be also fixed w/o change this line.

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h [hunk 3]
```diff
@@ -792,15 +789,14 @@ inline int32_t CalculateDPBSize(uint8_t & level_idc, int32_t width, int32_t heig
...
-            level_idc = H264VideoDecoderParams::H264_LEVEL_52;
-            break;
 #if (MFX_VERSION >= MFX_VERSION_NEXT)
         case H264VideoDecoderParams::H264_LEVEL_6:
         case H264VideoDecoderParams::H264_LEVEL_61:
         case H264VideoDecoderParams::H264_LEVEL_62:
-            level_idc = H264VideoDecoderParams::H264_LEVEL_MAX;
-            break;
 #endif
+            level_idc = INTERNAL_MAX_LEVEL;
```
Comment (guowillyy) [inline _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:797]: Agree, this should be the root cause, thanks!

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h (hunk 2 above)
Comment (guowillyy) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:731]: Suggest not to change this line, otherwise it will break AVC Level6+ support feature.

Comment (dmitryermilov) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:731]: @guowillyy , why will it break 6+?  Both cases H264VideoDecoderParams::H264_LEVEL_6* and default result in the same MaxDPBMbs = 696320.

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h [hunk 4]
```diff
@@ -792,15 +789,14 @@ inline int32_t CalculateDPBSize(uint8_t & level_idc, int32_t width, int32_t heig
         // can be used to calculate the DPB size.
         case H264VideoDecoderParams::H264_LEVEL_51:
         case H264VideoDecoderParams::H264_LEVEL_52:
-            level_idc = H264VideoDecoderParams::H264_LEVEL_52;
```
Comment (dmitry-gurulev) [inline _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:795]: I'd rather do something like
```
case H264VideoDecoderParams::H264_LEVEL_52:
#if (MFX_VERSION >= MFX_VERSION_NEXT)
        level_idc = H264VideoDecoderParams::H264_LEVEL_6;
#else
        level_idc = INTERNAL_MAX_LEVEL;
#endif
```

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h (hunk 2 above)
Comment (uartie) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:731]: Right, it will not break 6+ as @dmitryermilov pointed out.  But I will remove this change anyway, since it's unnecessary (gratuitous).

File: _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h (hunk 4 above)
Comment (uartie) [reply _studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h:795]: ok. I will change it.

**Comment by uartie** [comment]
Updated. Also improved commit message.

**Review by dmitryermilov — APPROVED** [review]
