### PR TITLE
mfx_h265_encode_hw_par: Resize default slice number according to Tiles

### LINKED ISSUE #1772: [Tiles][Slices][Encode][ffmpeg_qsv][sample_encode] Tile encoding fails with default slice number setting
Testing on ICL with the latest MSDK version:

**CMD:**
./**sample_encode** h265 -i 1080p_blue_sky.yuv -o msdk.h265 -w 1920 -h 1080 -trows 1 -tcols 3 -n 10

**ERROR:**
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/X11R7/iHD/vpg_driver/lib/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Encoding Sample Version 8.4.27.

Input file format	YUV420
Output video		HEVC
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	2890
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	balanced
Memory type	system
Media SDK impl		hw
Media SDK version	1.30

Processing started
[CODEC]:CRITICAL - ExecuteSliceLevel:2436: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - ExecuteEnc:4443: Slice level encoding failed.
[CODEC]:CRITICAL - Execute:587: MOS returned error, eStatus = 0x2
[LIBVA]:CRITICAL - EncodeInCodecHal:390: DDI:Failed in Codechal!
[LIBVA]:CRITICAL - EndPicture:81: DDI:DdiEncode_EncodeInCodecHal return failure.
sample_encode: /root/build/MediaSDK/_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_vaapi.cpp:1760: virtual mfxStatus MfxHwH265Encode::VAAPIEncoder::Execute(const MfxHwH265Encode::Task&, mfxHDLPair): Assertion `0x00000000 == vaSts' failed.
Aborted (core dumped)

Same issue could be observed when enabling Tile Encoding support in **FFmpeg QSV**.

**Analysis:**
The number of Slices should be:
nSlice = std::max(nSlice, nTile);
However, it  **won't be resized** if it equals to 1.(By default, the number of Slice is 1)

### PR DESCRIPTION
**Pull request by fulinjie**
Fix #1772.

Signed-off-by: Linjie Fu <linjie.fu@intel.com>

### CODE REVIEW

File: _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp [hunk 1]
```diff
@@ -515,12 +515,12 @@ mfxU16 MakeSlices(MfxVideoParam& par, mfxU32 SliceStructure)
     if (par.m_ext.CO2.NumMbPerSlice != 0)
         nSlice = CeilDiv(nLCU / nTile, par.m_ext.CO2.NumMbPerSlice) * nTile;
 
+    if (nSlice >= 1)
```
Comment (dmitryermilov) [inline _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp]: @fulinjie , sorry, I didn't get: why line #505 doesn't set correct num of slices?

Comment (fulinjie) [reply _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp]: That's because par.m_platform is MFX_HW_ICL_LP. (MFX_HW_ICL_LP = MFX_HW_ICL + 1)

Actually, I can see all the ICL devices listed in listLegalDevIDs would be registered as MFX_HW_ICL_LP.

As a consequence, is it more reasonable to change into:
if (par.m_platform <= MFX_HW_ICL_LP)

Comment (dmitryermilov) [reply _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp]: OMG

Comment (dmitryermilov) [reply _studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp]: Please re-work the PR as the attached one 
[0001-Slice-num-fix.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/3895888/0001-Slice-num-fix.txt)
